### ISSUE TITLE
POST /v2/sessions channel_id type inconsistency

### ISSUE THREAD

**Issue by danp** [heroku/logplex#119]
This interaction errors:

```
POST /v2/sessions
{ "channel_id": 12345, ... }

200
{ "url": "..." }

GET $url

400
'channel_id' missing
```

Changing `channel_id` to `"12345"` in the `POST` makes the flow work. As `channel_id` is json-encoded as a number everywhere else I've seen this is surprising. I think the least intrusive change would be to have this endpoint accept a numeric `channel_id` and coerce as necessary.

**Comment by agnaite** [comment]
closing as part of the [Retire Logplex OKR](https://salesforce.quip.com/UfD4AwLYWZzW).
