### ISSUE TITLE
Expiring redis spool key deletes channel from ets

### ISSUE THREAD

**Issue by mkrysiak** [heroku/logplex#147]
I'm not sure if this is a bug or desired behavior.  redis_helper:build_push_msg creates a ch:channelId:spool key in redis with an exipration, and when that key expires, nsync_callback:handle({cmd, "del", [<<"ch:", Suffix/binary>> | Args]}) is called, which deletes the channelid from ets.  However, data associated with that channelId remains, such as tokens, drains, and the redis drain:channelId:data key.  Is this desired?  My guess is that the channelid should only be deleted from ets when a call is made to the API, not when a spool key expires.

**Comment by voidlock** [comment]
@mkrysiak That is in indeed a bug. Thanks for finding this. If you feel like submitting a patch to resolve the issue we will review and merge it promptly.

A quick workaround is to use a different redis instance to store the logs buffers. This can be controlled via environment variables.

For instance, running two redis servers locally:
```
LOGPLEX_CONFIG_REDIS_URL="redis://localhost:6379"
LOGPLEX_SHARD_URLS="redis://localhost:6380"
```

**Comment by rcsavage** [comment]
Is this project active?

**Comment by Tomcoong** [comment]
Delta Emblem.

**Comment by agnaite** [comment]
closing as part of the [Retire Logplex OKR](https://salesforce.quip.com/UfD4AwLYWZzW).
