### ISSUE TITLE
Question: How to best deal with an app that produces too many logs?

### ISSUE THREAD

**Issue by jesseshieh** [heroku/logplex#199]
I'm running my own instance of Logplex and I have a bunch of Elixir apps sending it logs. Normally all is well, but sometimes the (buggy) Elixir apps will go into an infinite crash loop and generate a TON of logs. The Logplex machine doesn't handle this very well: CPU goes to 100% and oddly enough ETS entries start disappearing among other things.

This happens even if there are no tails or drains on the channel. 

My understanding is that logs are not throttled or rate limited when Logplex receives them and are instead only dropped when the logs are written out to tails, drains, redis, or the firehose. In my case though, this doesn't prevent the CPU from getting pegged or prevent weird ETS behavior. 

I wanted to ask and find out if there is a proper way to deal with an app that produces waaaaay too many logs. Any advice is extremely appreciated! Thanks!

**Comment by agnaite** [comment]
closing as part of the [Retire Logplex OKR](https://salesforce.quip.com/UfD4AwLYWZzW).
