### ISSUE TITLE
Syslog messages are missing a NILVALUE for the STRUCTURED-DATA field.

### ISSUE THREAD

**Issue by dreid** [heroku/logplex#204]
The `logplex_syslog_utils:rfc5424` function used to format syslog messages https://github.com/heroku/logplex/blob/master/src/logplex_syslog_utils.erl#L34-L46 doesn't set a NILVALUE (`-`) for the `STRUCTURED-DATA` field.

The heroku log drains docs claim that logplex sends "syslog formatted messages".

However https://tools.ietf.org/html/rfc5424#section-6 defines `SYSLOG-MSG` as:

```
      SYSLOG-MSG      = HEADER SP STRUCTURED-DATA [SP MSG]
```

and `STRUCTURED-DATA` is defined as:

```
      STRUCTURED-DATA = NILVALUE / 1*SD-ELEMENT
      SD-ELEMENT      = "[" SD-ID *(SP SD-PARAM) "]"
      SD-PARAM        = PARAM-NAME "=" %d34 PARAM-VALUE %d34
      SD-ID           = SD-NAME
      PARAM-NAME      = SD-NAME
      PARAM-VALUE     = UTF-8-STRING ; characters '"', '\' and
                                     ; ']' MUST be escaped.
      SD-NAME         = 1*32PRINTUSASCII
                        ; except '=', SP, ']', %d34 (")
```

Making `STRUCTURED-DATA` a required part of the message.

Indeed in section 6.3: https://tools.ietf.org/html/rfc5424#section-6.3

```
   STRUCTURED-DATA can contain zero, one, or multiple structured data
   elements, which are referred to as "SD-ELEMENT" in this document.

   In case of zero structured data elements, the STRUCTURED-DATA field
   MUST contain the NILVALUE.
```

At the very least logplex/logdrains docs should clearly note this violation and specify the message format.

Better of course would be a fix and some upgrade path, but clearly the number of adhoc implementations of the logplex message format are going to make that difficult.

**Comment by archaelus** [comment]
It should. The reason it doesn't is backwards compatibility with an ancient mistake inside Heroku's log pipeline. This bug has been noted numerous times at Heroku, and Heroku is (probably?) the only organization needing that backwards compatibility.

Imo, it should be fixed by default and a Heroku-only backwards compatibility mode should be a compile/runtime option.

**Comment by agnaite** [comment]
closing as part of the [Retire Logplex OKR](https://salesforce.quip.com/UfD4AwLYWZzW).
