### ISSUE TITLE
HTTP input returns 204 when procid is missing

### ISSUE THREAD

**Issue by ryansmith3136** [heroku/logplex#22]
If I include a blank field for procid, HTTP inputs return a 204. However, if I tail the log stream, the messages without the procid field are not found. I propose that your HTTP input API return a 4XX when the procid is missing since it is required for logs to make it through.

**Comment by agnaite** [comment]
closing as part of the [Retire Logplex OKR](https://salesforce.quip.com/UfD4AwLYWZzW).
