### ISSUE TITLE
Are Syslog UDP Drains Fully Supported?

### ISSUE THREAD

**Issue by blaskovicz** [heroku/logplex#228]
I've created a channel with 3 tokens (eg - name: "someapp", token: "t.some-uuid") and a single drain of the form `udpsyslog://<hostname>:<port>` and have netcat running, listening for udp logs (`while true; do nc --telnet --verbose --udp -l -p <port>; done`).

When I log to this channel using the token, I see nothing in netcat. Also, I see no udp/tcp traffic when looking running tcpdump on the port (`sudo tcpdump -i any  port <port>-A`).  If, instead, I have netcat running in tcp mode (the default) and create a regular `syslog://` or `http://` drain, I see log traffic immediately.

I'm using a rather old version of Logplex (v89), but I'm unsure if the [udp-specific changes](https://github.com/heroku/logplex/search?q=udp&type=Commits&utf8=%E2%9C%93) since then would solve this issue.

Thanks for taking a look!

**Comment by agnaite** [comment]
closing as part of the [Retire Logplex OKR](https://salesforce.quip.com/UfD4AwLYWZzW).
