### ISSUE TITLE
Consider `text/plain` `Content-Type` for logs response

### ISSUE THREAD

**Issue by brandur** [heroku/logplex#68]
When getting logs via a Logplex session, consider returning the more apt `text/plain` `Content-Type` (currently it's `text/html`). *This feedback came in via [support ticket](https://support.heroku.com/tickets/105150?col=0&page=1).

**Comment by agnaite** [comment]
closing as part of the [Retire Logplex OKR](https://salesforce.quip.com/UfD4AwLYWZzW).
