### ISSUE TITLE
Protocol of 'log tail' api is unclear

### ISSUE THREAD

**Issue by jordansissel** [heroku/logplex#7]
The API for core/logplex appears to emit 'chunks' but there seems no meaning of each 'chunk'. Solving this will probably require some definition of a protocol, but I'll leave implementation ideas out of this :)

I've observed the following of a 'chunk' emitted on different occasions:
- it's an empty string
- it's a single event
- it's multiple events delimited by newline

This observation was while writing some integration monitoring for logplex. I also dug into the Heroku::Client ruby code, and both ['empty string'](https://github.com/heroku/heroku/blob/master/lib/heroku/command/logs.rb#L31) and ['multiple events in a chunk'](https://github.com/heroku/heroku/blob/master/lib/heroku/command/logs.rb#L78) are worked round.

**Comment by agnaite** [comment]
closing as part of the [Retire Logplex OKR](https://salesforce.quip.com/UfD4AwLYWZzW).
