### ISSUE TITLE
Does not support Redis 2.8.x

### ISSUE THREAD

**Issue by errordeveloper** [heroku/logplex#92]
I got it to compile with a couple of simple tweaks:
- errordeveloper/logplex@0981502f25b9a30c6706b9e4d5c468c756a93e2f
- errordeveloper/nsync@3b5f7eaa74948a0826321a1147effdb610b25f1d

But it fails to run with this:

```
gen_server <0.150.0> terminated with reason: {error,vsn_not_supported}
CRASH REPORT Process <0.150.0> with 0 neighbours exited with reason: {error,vsn_not_supported} in gen_server:terminate/6 line 746
Supervisor logplex_sup had child nsync started with nsync:start_link([{callback,{nsync_callback,handle,[]}},{host,"127.0.0.1"},{port,6379},{pass,undefined}]) at <0.150.0> exit with reason {error,vsn_not_supported} in context child_terminated
gen_server <0.178.0> terminated with reason: {error,vsn_not_supported}
CRASH REPORT Process <0.178.0> with 0 neighbours exited with reason: {error,vsn_not_supported} in gen_server:terminate/6 line 746
** System running to use fully qualified hostnames **
** Hostname dds-492c55 is illegal **
```

I believe the hostname is not being the issue for `vsn_not_supported` error, right?

**Comment by agnaite** [comment]
closing as part of the [Retire Logplex OKR](https://salesforce.quip.com/UfD4AwLYWZzW).

**Comment by ferd** [comment]
This is an Open Source project that is also used outside of Heroku.
@agnaite I know you're probably not the only person in charge there, but it might be interesting to know if Heroku/Salesforce has some sort of plan regarding future project control if you're not going to be staffing it in the future.

**Comment by tsloughter** [comment]
May be time to move logplex to https://github.com/logplex :) and add some new people to that org.

**Comment by agnaite** [comment]
> This is an Open Source project that is also used outside of Heroku.
> @agnaite I know you're probably not the only person in charge there, but it might be interesting to know if Heroku/Salesforce has some sort of plan regarding future project control if you're not going to be staffing it in the future.

Yes, apologies @ferd - oversight regarding this being OSS.
