### ISSUE TITLE
Fail to reconnect to redis on timeout

### ISSUE THREAD

**Issue by cbarraford** [heroku/logplex#93]
I noticed that if you have the attribute `timeout` configured in redis (`redis.conf`), meaning the value is larger than 0 (0 is disabled), that when redis times out the logplex connection, logplex stops saving logs to the db and still responds with a 204 response code. This doesn't seem to affect channels or tokens though, only saving new logs.

The easy workaround for now is to set `timeout` to `0` in `/etc/redis/redis.conf`, but logplex should see the connection has been lost and reconnect.

**Comment by agnaite** [comment]
closing as part of the [Retire Logplex OKR](https://salesforce.quip.com/UfD4AwLYWZzW).
