### ISSUE TITLE
Add CORS Support

### ISSUE THREAD

**Issue by jamesward** [heroku/logplex#96]
I'm not sure if this is the right place to file feature requests for the logplex http endpoint, but it would be great to have CORS support for the log streams, like: https://logplex.heroku.com/sessions/1234

**Comment by karpikov** [comment]
Yes, this is will good function. Now try with javascript make show logs for dyno with HEROKU API - and without CORS it not possible, i need set log stream as src for iframe (

**Comment by agnaite** [comment]
closing as part of the [Retire Logplex OKR](https://salesforce.quip.com/UfD4AwLYWZzW).
